import type {
  FaqItem,
  GalleryImage,
  LandingSectionId,
  PendingInformation,
} from "@/types/landing";
import { createWhatsAppUrl, whatsappMessages } from "@/lib/whatsapp";

export const landingSectionIds = [
  "hero",
  "about",
  "features",
  "gallery",
  "location",
  "faq",
  "cta",
] satisfies LandingSectionId[];

export const navigationItems = [
  { id: "about", label: "O Rancho" },
  { id: "features", label: "Estrutura" },
  { id: "gallery", label: "Galeria" },
  { id: "location", label: "Localização" },
  { id: "cta", label: "Contato" },
] satisfies { id: LandingSectionId; label: string }[];

export const landingContent = {
  name: "Rancho Xeirin",
  plannedH1: "Rancho Xeirin em Corumbá IV",
  location: {
    lake: "Lago Corumbá IV",
    condominium: "Condomínio Recanto do Sabiá",
    distances: ["cerca de 90 km de Brasília", "cerca de 110 km de Goiânia"],
    security: ["condomínio fechado", "segurança 24 horas"],
    lakeAccess: "descida para barcos, lanchas ou jet-ski a poucos metros",
  },
  contact: {
    whatsapp: "+55 61 99664-3612",
    whatsappMessage: whatsappMessages.general,
    whatsappUrl: createWhatsAppUrl("general"),
    availabilityMessage: whatsappMessages.reservation,
    availabilityUrl: createWhatsAppUrl("reservation"),
    locationMessage: whatsappMessages.location,
    locationUrl: createWhatsAppUrl("location"),
  },
  hero: {
    eyebrow: "Lago Corumbá IV · Recanto do Sabiá",
    title: "Rancho Xeirin",
    subtitle:
      "Seu refúgio para descansar, reunir a família e aproveitar bons momentos às margens do Lago Corumbá IV.",
    supportingText:
      "Natureza, piscina aquecida, sauna, área gourmet e muito espaço para aproveitar.",
    primaryCta: "Reservar pelo WhatsApp",
    secondaryCta: "Conhecer o Rancho",
    scrollLabel: "Role para conhecer",
  },
  about: {
    eyebrow: "Curta a Natureza",
    title: "Um lugar para desacelerar",
    paragraphs: [
      "O Rancho Xeirin tem tudo que você precisa para fugir do corre-corre da cidade e recarregar as baterias.",
      "Às margens do Lago Corumbá IV, o Rancho Xeirin combina natureza, conforto e uma atmosfera acolhedora para momentos especiais com família e amigos.",
      "Alugamos o espaço por temporadas e fins-de-semanas para sua família e amigos desfrutar do que há de melhor em nossa região.",
    ],
  },
  calls: [
    "A melhor opção de lazer",
    "Às margens do Lago Corumbá IV",
    "Curta a Natureza",
    "Faça sua reserva",
    "Venha relaxar num ambiente rústico e tranquilo",
    "Sinta-se na casa da Vovó",
    "O Rancho Xeirin tem tudo que você precisa pra fugir do corre-corre da cidade e recarregar as baterias",
  ],
  descriptions: [
    "Situado a cerca de 90Km de Brasilia, estamos localizados às margens do Lago de Corumbá IV, no Condomínio Recanto do Sabiá!",
    "Rancho em condomínio fechado, com segurança 24 horas e acomodações que proporcionam total conforto e privacidade para sua estadia.",
    "Ao contrário do que você possa imaginar, o custo de estadia com a gente cabe no seu bolso. Solicite um orçamento e surpreenda-se!",
    "Situados a cerca de 90km de Brasília e 110km de Goiânia, às margens do Lago Corumbá IV, temos a sua disposição um local privilegiado para seu descanso ou diversão.",
    "Alugamos o espaço por temporadas e fins-de-semanas para sua família e amigos desfrutar do que há de melhor em nossa região.",
  ],
  amenities: [
    "4 ou 6 suítes, dependendo da quantidade de pessoas",
    "2 camas de casal em cada suíte",
    "ampla sala de TV",
    "piscina com ofurô aquecida",
    "aquecimento solar e elétrico",
    "sauna",
    "campinho de futebol 3x3",
    "churrasqueira",
    "Wi-Fi",
    "TV Sky",
    "estacionamento para cerca de 10 carros",
    "portão elétrico",
    "cozinha equipada",
    "panelas",
    "pratos",
    "talheres",
    "copos",
    "sanduicheira",
    "liquidificador",
    "micro-ondas",
    "forno elétrico",
    "forno a gás",
    "2 geladeiras duplex",
    "cervejeira",
    "descida para barcos, lanchas ou jet-ski a poucos metros",
  ],
  featureGroups: [
    {
      title: "Descanso e lazer",
      items: [
        "Piscina com ofurô aquecida",
        "Sauna",
        "Campinho de futebol 3x3",
        "Acesso próximo ao Lago Corumbá IV",
      ],
    },
    {
      title: "Convivência",
      items: [
        "Área gourmet com churrasqueira",
        "Cozinha equipada",
        "Ampla sala de TV",
        "Wi-Fi",
      ],
    },
    {
      title: "Estrutura",
      items: [
        "4 ou 6 suítes, dependendo da quantidade de pessoas",
        "2 camas de casal em cada suíte",
        "TV Sky",
        "Estacionamento para cerca de 10 carros",
        "Portão elétrico",
      ],
    },
  ],
  leisure: {
    title: "Piscina, sauna e momentos de descanso",
    text: "O espaço possui piscina com ofurô aquecida, sauna e integração com a área externa para aproveitar o dia com tranquilidade.",
    highlights: [
      "Piscina com ofurô aquecida",
      "Aquecimento solar e elétrico",
      "Sauna com vista para a piscina",
    ],
  },
  gourmet: {
    title: "Tudo preparado para reunir quem você gosta",
    text: "A área gourmet reúne churrasqueira, cozinha equipada e utensílios para preparar refeições especiais com família e amigos.",
    highlights: [
      "Churrasqueira",
      "Forno elétrico e forno a gás",
      "2 geladeiras duplex",
      "Cervejeira",
      "Panelas, pratos, talheres e copos",
      "Sanduicheira, liquidificador e micro-ondas",
    ],
  },
  lake: {
    title: "Às margens do Lago Corumbá IV",
    text: "No Condomínio Recanto do Sabiá, o Rancho Xeirin está às margens do Lago Corumbá IV, em condomínio fechado com segurança 24 horas.",
    details: [
      "Condomínio Recanto do Sabiá",
      "cerca de 90 km de Brasília",
      "cerca de 110 km de Goiânia",
      "descida para barcos, lanchas ou jet-ski a poucos metros",
      "condomínio fechado",
      "segurança 24 horas",
    ],
    directions: {
      title: "Como chegar",
      text: "O Rancho Xeirin está localizado no Condomínio Recanto do Sabiá, às margens do Lago Corumbá IV.",
      cta: "Pedir localização pelo WhatsApp",
    },
  },
  cta: {
    title: "Seu próximo fim de semana pode ser aqui.",
    text: "Fale com o Rancho Xeirin pelo WhatsApp e consulte disponibilidade.",
    button: "Consultar disponibilidade",
  },
  assets: {
    heroVideoMp4: "/videos/rancho-xeirin-hero.mp4",
    heroVideoWebm: "/videos/rancho-xeirin-hero.webm",
    heroFallback: "/images/gallery/masonry_item_3.avif",
    brandHeader: "/images/brand/cabecalho_corumba.avif",
    locationHeader: "/images/location/heading_bg.avif",
    icons: {
      whatsapp: "/icons/icone_whatsapp.png",
      instagram: "/icons/icone_instagram.png",
      facebook: "/icons/icone_facebook.png",
      googleMaps: "/icons/icone_googlemaps.png",
      phone: "/icons/icone_telefone.png",
      email: "/icons/icone_email.png",
    },
  },
} as const;

export const pendingInformation = [
  { key: "capacity", label: "capacidade máxima", status: "pendente" },
  {
    key: "suiteCountByBooking",
    label: "número final de suítes por reserva",
    status: "pendente",
  },
  { key: "pricing", label: "valores", status: "pendente" },
  { key: "checkIn", label: "check-in", status: "pendente" },
  { key: "checkOut", label: "check-out", status: "pendente" },
  { key: "pets", label: "pets", status: "pendente" },
  { key: "events", label: "eventos", status: "pendente" },
  { key: "bedLinen", label: "roupa de cama", status: "pendente" },
  { key: "bathLinen", label: "roupa de banho", status: "pendente" },
  { key: "address", label: "endereço completo", status: "pendente" },
  { key: "instagram", label: "Instagram", status: "pendente" },
  { key: "facebook", label: "Facebook", status: "pendente" },
  { key: "email", label: "email", status: "pendente" },
  {
    key: "alternativePhone",
    label: "telefone alternativo",
    status: "pendente",
  },
] satisfies PendingInformation[];

export const galleryImages = [
  {
    file: "/images/gallery/masonry_item_3.avif",
    category: "piscina",
    title: "Piscina com espreguiçadeiras",
    description: "Piscina externa com espreguiçadeiras e área arborizada.",
    alt: "Piscina do Rancho Xeirin com espreguiçadeiras e palmeiras ao redor",
    width: 466,
    height: 360,
  },
  {
    file: "/images/gallery/masonry_item_6.avif",
    category: "pôr do sol",
    title: "Pôr do sol no lago",
    description: "Sol se pondo sobre as águas do Lago Corumbá IV.",
    alt: "Pôr do sol sobre o Lago Corumbá IV visto do Rancho Xeirin",
    width: 466,
    height: 360,
  },
  {
    file: "/images/gallery/masonry_item_4.avif",
    category: "área gourmet",
    title: "Varanda coberta integrada",
    description: "Área coberta ampla com mesas, geladeiras e rede suspensa.",
    alt: "Varanda coberta ampla do Rancho Xeirin com mesas, geladeiras e rede",
    width: 466,
    height: 360,
  },
  {
    file: "/images/gallery/masonry_item_14.avif",
    category: "lago",
    title: "Acesso próximo ao lago",
    description: "Vista panorâmica do lago a partir de uma área de acesso.",
    alt: "Vista panorâmica do Lago Corumbá IV com caminho de acesso próximo ao Rancho Xeirin",
    width: 932,
    height: 360,
  },
  {
    file: "/images/gallery/masonry_item_7.avif",
    category: "área externa",
    title: "Fachada e área gramada",
    description: "Vista externa da casa com gramado e palmeiras.",
    alt: "Área externa do Rancho Xeirin com fachada, gramado e palmeiras",
    width: 932,
    height: 360,
  },
  {
    file: "/images/gallery/masonry_item_9.avif",
    category: "sauna",
    title: "Sauna com vista para piscina",
    description: "Sauna revestida em pastilhas com frente de vidro.",
    alt: "Sauna do Rancho Xeirin com frente de vidro e vista para a piscina",
    width: 466,
    height: 360,
  },
  {
    file: "/images/gallery/masonry_item_5.avif",
    category: "cozinha",
    title: "Churrasqueira e cozinha",
    description: "Churrasqueira de tijolo e bancada de cozinha equipada.",
    alt: "Churrasqueira de tijolo e bancada de cozinha no Rancho Xeirin",
    width: 466,
    height: 360,
  },
  {
    file: "/images/gallery/masonry_item_2.avif",
    category: "lago",
    title: "Vista para o Lago Corumbá IV",
    description: "Vista lateral da casa em direção ao lago.",
    alt: "Vista do Rancho Xeirin para o Lago Corumbá IV ao entardecer",
    width: 466,
    height: 360,
  },
  {
    file: "/images/gallery/masonry_item_1.avif",
    category: "área gourmet",
    title: "Mesa rústica na área gourmet",
    description: "Ambiente coberto com mesa de madeira e churrasqueira ao fundo.",
    alt: "Mesa rústica de madeira na área gourmet do Rancho Xeirin com churrasqueira ao fundo",
    width: 466,
    height: 720,
  },
  {
    file: "/images/gallery/masonry_item_8.avif",
    category: "quartos",
    title: "Quarto com camas de casal",
    description: "Quarto com duas camas de casal e banheiro integrado.",
    alt: "Quarto do Rancho Xeirin com duas camas de casal e banheiro integrado",
    width: 932,
    height: 360,
  },
  {
    file: "/images/gallery/masonry_item_10.avif",
    category: "lazer",
    title: "Área esportiva gramada",
    description: "Espaço gramado cercado para lazer.",
    alt: "Área esportiva gramada e cercada no Rancho Xeirin",
    width: 466,
    height: 360,
  },
  {
    file: "/images/gallery/masonry_item_11.avif",
    category: "sala",
    title: "Sala de TV",
    description: "Sala com sofás, painel e televisão.",
    alt: "Sala de TV do Rancho Xeirin com sofás e painel para televisão",
    width: 466,
    height: 360,
  },
  {
    file: "/images/gallery/masonry_item_12.avif",
    category: "lago",
    title: "Varanda com vista",
    description: "Mesa externa com vista em direção ao lago.",
    alt: "Mesa externa na varanda do Rancho Xeirin com vista para o lago",
    width: 466,
    height: 360,
  },
  {
    file: "/images/gallery/masonry_item_13.avif",
    category: "natureza",
    title: "Natureza no rancho",
    description: "Registro da natureza presente no gramado.",
    alt: "Animal no gramado do Rancho Xeirin representando a natureza local",
    width: 466,
    height: 360,
  },
  {
    file: "/images/gallery/masonry_item_15.avif",
    category: "piscina",
    title: "Piscina externa",
    description: "Piscina próxima à área coberta do rancho.",
    alt: "Piscina externa do Rancho Xeirin próxima à área coberta",
    width: 466,
    height: 360,
  },
  {
    file: "/images/gallery/masonry_item_16.avif",
    category: "cozinha",
    title: "Bancada da cozinha",
    description: "Bancada com banquetas, churrasqueira e forno.",
    alt: "Bancada da cozinha do Rancho Xeirin com banquetas, churrasqueira e forno",
    width: 466,
    height: 360,
  },
  {
    file: "/images/gallery/masonry_item_17.avif",
    category: "piscina",
    title: "Piscina integrada à área gourmet",
    description: "Piscina ao lado da varanda coberta e área de convivência.",
    alt: "Piscina do Rancho Xeirin integrada à varanda coberta e área gourmet",
    width: 466,
    height: 360,
  },
  {
    file: "/images/gallery/about_us.avif",
    category: "piscina",
    title: "Piscina e descanso",
    description: "Piscina com espreguiçadeira e palmeiras.",
    alt: "Piscina do Rancho Xeirin com espreguiçadeira e palmeiras ao fundo",
    width: 700,
    height: 410,
  },
] satisfies GalleryImage[];

export const faqItems = [
  {
    question: "Em qual região fica o Rancho Xeirin?",
    answer:
      "O Rancho Xeirin fica às margens do Lago Corumbá IV, no Condomínio Recanto do Sabiá.",
  },
  {
    question: "O Rancho possui piscina?",
    answer:
      "Sim. O espaço possui piscina com ofurô aquecida, com aquecimento solar e elétrico.",
  },
  {
    question: "Possui sauna?",
    answer: "Sim. O Rancho Xeirin possui sauna.",
  },
  {
    question: "Tem cozinha equipada?",
    answer:
      "Sim. A cozinha conta com panelas, pratos, talheres, copos, sanduicheira, liquidificador, micro-ondas, forno elétrico, forno a gás, 2 geladeiras duplex e cervejeira.",
  },
  {
    question: "Tem Wi-Fi?",
    answer: "Sim. O Rancho Xeirin possui Wi-Fi.",
  },
  {
    question: "Tem estacionamento?",
    answer: "Sim. Há estacionamento para cerca de 10 carros.",
  },
  {
    question: "Há acesso próximo para barcos ou jet-ski?",
    answer:
      "Sim. Existe descida para barcos, lanchas ou jet-ski a poucos metros.",
  },
] satisfies FaqItem[];
